name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
 
      - name: Build with Gradle
        run: ./gradlew build         

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get commit SHA
        id: get_commit_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build the Docker image
        run: |
          version="${{ steps.get_commit_sha.outputs.sha }}"
          docker buildx inspect --bootstrap
          docker buildx build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/presidents:${version} .
          docker push ${{ secrets.DOCKER_USERNAME }}/presidents:${version}